### ISSUE TITLE
the INSTALLmd mentions running ../configure, but its not there.

### ISSUE THREAD

**Issue by netskink** [accellera-official/systemc#29]
Perhaps the installation instructions need to mention automake.  In my case, I tried to do `automake --add-missing` in the root dir but that fails to make a configure script.

**Comment by netskink** [comment]
Ahh, later in the INSTALL doc it mentions how to generate a configure script. `./config/bootstrap`  Afterwards, from the objdir dir I was able to do ../configure.

**Comment by basarts** [comment]
Hi John,

There is a difference between the [`master`](https://github.com/accellera-official/systemc/tree/master) branch and the [`release`](https://github.com/accellera-official/systemc/tree/release) branch. The latter does contain the configure script.

-- 
Bas

**Comment by netskink** [comment]
Ahh, that makes sense.  Thanks for pointing that out.  After the clone, I should have done a git checkout <some release tag>.  I appreciate the response.
