### ISSUE TITLE
`configure` is not available.

### ISSUE THREAD

**Issue by parsanoori** [accellera-official/systemc#31]
The script `configure` said in [here](https://github.com/accellera-official/systemc/blob/master/INSTALL.md#basic-systemc-installation) is not available in the top level directory.

**Comment by AmeyaVS** [comment]
As discussed in: [https://github.com/accellera-official/systemc/issues/29](https://github.com/accellera-official/systemc/issues/29)

You need to run the  `config/bootstrap` to generate the configure script.

**Comment by parsanoori** [comment]
The documentation for the installation process must get updated then.

**Comment by AmeyaVS** [comment]
I would recommend using the CMake based build and install flow.

**Comment by parsanoori** [comment]
The `configure` file is on the `release` branch.
