### ISSUE TITLE
Error on running `make`: `qtmds.s:77:19: error: unexpected token in '.section' directive`

### ISSUE THREAD

**Issue by parsanoori** [accellera-official/systemc#32]
On running `make` using the given [installation guide](https://github.com/accellera-official/systemc/blob/release/INSTALL.md#installation-notes-for-unix), I get:
```
qtmds.s:77:19: error: unexpected token in '.section' directive
.section .note.GNU-stack,"",%progbits
                  ^
make[4]: *** [libqt_la-qtmds.lo] Error 1
make[3]: *** [all] Error 2
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

**Comment by AmeyaVS** [comment]
What system are you using to build the SystemC library?(OS, underlying Arch.)

**Comment by parsanoori** [comment]
Thanks got the SystemC built using the cmake.
But the `make check` is not working.
