### ISSUE TITLE
Apple silicon support

### ISSUE THREAD

**Issue by chenrui333** [accellera-official/systemc#39]
👋 does the project support apple silicon? (per [system 2.3.2 build](https://github.com/Homebrew/homebrew-core/blob/master/Formula/systemc.rb#L13-L23) on the homebrew side, it seems building out fine). Thanks!

**Comment by ahmedsamiruci** [comment]
@chenrui333 Did it work for you? I tried to install it on my M1 machine, but I failed.

**Comment by wrighton** [comment]
https://forums.accellera.org/topic/6984-running-systemc-on-new-apple-m1-silicon/

Describes how to hack it to work.

**Comment by chenrui333** [comment]
I can build out fine with 2.3.4 on ventura arm, see [this PR](https://github.com/Homebrew/homebrew-core/pull/123633).

Closing this now.
