### ISSUE TITLE
How to link systemc with CMake? 

### ISSUE THREAD

**Issue by 492859780** [accellera-official/systemc#42]
There is no include directory in the project, so my hello world demo in another directory can't find header files using CMake. How do l link systemc with CMake in other directory.

**Comment by AmeyaVS** [comment]
Did you try the steps mentioned [here](https://github.com/accellera-official/systemc/blob/master/cmake/INSTALL_USING_CMAKE) on building using CMake?

**Comment by 492859780** [comment]
> Did you try the steps mentioned [here](https://github.com/accellera-official/systemc/blob/master/cmake/INSTALL_USING_CMAKE) on building using CMake?

I solved the problem with these steps, thanks.

**Comment by AmeyaVS** [comment]
@492859780 , Probably close the issue. If you are able to proceed now.
