### ISSUE TITLE
Some questions about assignment

### ISSUE THREAD

**Issue by Yonghao-Tan** [accellera-official/systemc#43]
Hi, I'm a rookie studying systemc. In systemc, an input is sc_in<sc_uint<8>> a, a local variable is sc_uint<8> b. I want to ask what is the difference between b = a and b = a.read()? Also, if an input is sc_out<sc_uint<8>> a, a local variable is sc_uint<8> b, what is the difference between a = b and a.write(b)? Thank you.

**Comment by AmeyaVS** [comment]
I think it would be better to take this conversation in the SystemC forum here:
https://forums.accellera.org/
