### ISSUE TITLE
Miss Makefile.in in src folder

### ISSUE THREAD

**Issue by BrianLChen** [accellera-official/systemc#45]
Hi,

I recently have some problem when I try to install systemC in my machine, when I do "../configure" it will report an error of "cannot fine input file: `src/Makefile.in'.

I noticed that in the newest version, there is no file called "makefile.in", which used to appear in the previous version.

**Comment by merkaG** [comment]
Hello,

You still have the issue?
If so, did try with config/bootstrap?
You may need to cleanup your env before that. See doc.

I am able to build / install latest version as of today on Debian 11.

regards,

**Comment by merkaG** [comment]
OK, from aother issue I see what you mean.
Indeed, i can see the failure when I download the package .tar.gz

Still, you can use the workaround I propose with the bootstrapping

**Comment by merkaG** [comment]
should be marked duplicate to issue https://github.com/accellera-official/systemc/issues/40

**Comment by chenhaoc** [comment]
I get the same issue, here is my solution.
`autoreconf -vfi` then `cd objdir`  do `../configure` will work.

**Comment by lmailletcontoz** [comment]
Fixed in SystemC 3.0.0 release
