### ISSUE TITLE
Typo: SC_UNITIALIZED should be SC_UNINITIALIZED

### ISSUE THREAD

**Issue by dcblack** [accellera-official/systemc#46]
Not much else to say. I did do a search in case it already existed, but it does not.

**Comment by maehne** [comment]
I think this is resolved in our internal repository OSCI-WG/systemc. I only found one trace of the typo in a [code comment](https://github.com/OSCI-WG/systemc/blob/b1915b6e4a2f16eba29f2bc6dc9a8497a889be51/src/sysc/kernel/sc_simcontext.h#L1041).

@AndrewGoodrich: Could you maybe fix it? Then, I think we can close this issue as resolved.

**Comment by AndrewGoodrich** [comment]
Torsten issue 46 is closed in OSCI-WG/systemc, is there a different number for this issue?

Thanks,
   Andy

**Comment by AndrewGoodrich** [comment]
Obviously I found it now, wrong repository. David, can you close this?

**Comment by lmailletcontoz** [comment]
Fixed in SystemC 3.0.0 release
