### ISSUE TITLE
Broken CMake Configuration

### ISSUE THREAD

**Issue by AmeyaVS** [accellera-official/systemc#47]
It seems the CMake Configuration:
`BUILD_SOURCE_DOCUMENTATION` is broken.
Even After enabling the said configuration parameter to ON.
I am not able to observe any Doxygen Generated HTML Documentation for the SystemC sources.

**Comment by AmeyaVS** [comment]
Yes, I have them installed.

**Comment by AmeyaVS** [comment]
Seems like this and other associated commits disabled the Doxygen Documentation generations: c5ba24e

**Comment by dcblack** [comment]
To re-enable, simply add the following command to the top-level CMakeLists.txt file:

```cmake
# Place this after add_subdirectory (srcs) 
add_subdirectory (docs) 
```

As to why it was removed, I am uncertain.
