### ISSUE TITLE
Make check fails after building with cmake on macOS M1

### ISSUE THREAD

**Issue by dcracan** [accellera-official/systemc#56]
Hi all,

I'm building systemc with cmake and the process completes with no issues. However I cannot run any test bench:
_dyld[89728]: missing symbol called_ 
even make check fails for all tests. 
I've compiled with clang:
_Apple clang version 12.0.5 (clang-1205.0.22.9)
Target: arm64-apple-darwin22.5.0
Thread model: posix_

Any suggestions are more than welcome.

Update: I've made make check to pass by building with shared libraries ON, however when I try to build a systemc-ams test bench I still get the missing symbol called error.

**Comment by lmailletcontoz** [comment]
Fixed in SystemC 3.0.0. release
