### ISSUE TITLE
Undefind reference to sc_core::sc_api_version_2_3_3cxx201103L ...

### ISSUE THREAD

**Issue by mazhar1998** [accellera-official/systemc#60]
[Issues1.pdf](https://github.com/accellera-official/systemc/files/13173359/Issues1.pdf)
What is the solution 
Thanks and regards 
Mazhar

**Comment by AmeyaVS** [comment]
This issue is due to mismatched C++ Standard feature flags enabled for your module buld vs the SystemC compilation flags.

Please check the `-std=c++xx` flag when building your project, where xx is the value between 11,14,17, etc.

**Comment by mazhar1998** [comment]
Building using 11 standard only still facing same issue

**Comment by AmeyaVS** [comment]
With which c++ standard flags was the SystemC library built with?
You can check the SystemC forum for similar discussion and possible solution.

**Comment by lmailletcontoz** [comment]
Closed as answered.
