### ISSUE TITLE
Support for building Windows DLLs with cmake

### ISSUE THREAD

**Issue by aut0** [accellera-official/systemc#64]
Currently, the cmake build flow does not allow building a Windows DLL.
This should actually be possible.
This contains a very small patch set to enable it: https://github.com/OSCI-WG/systemc/pull/265

Maybe someone could test this on Windows?
In order to test set -DBUILD_SHARED_LIBS=ON and change this OFF to an ON: https://github.com/accellera-official/systemc/blob/1c3b138df6c608a002673f76d598692d45fe7e55/CMakeLists.txt#L267

**Comment by timsnyder** [comment]
I'd try this on the Windows build I just added to conda-forge  but I don't have permissions to see OSCI-WG/systemc#265 and grab the patch there.  If you add your patch in a PR to conda-forge/systemc-feedstock in the [recipe/patches](https://github.com/conda-forge/systemc-feedstock/tree/main/recipe/patches) subdirectory, I can add the rest of the conda-forge stuff around it and try it out in CI.

**Comment by barnasc** [comment]
Should be fixed in https://github.com/accellera-official/systemc/commit/40ae61d45553f5528c9039bd4a97564d69da54b3.  I will close the issue, feel free to reopen if the issue remains
