### ISSUE TITLE
c++ syntax problem for SC_CTOR

### ISSUE THREAD

**Issue by lmxlovecode** [accellera-official/systemc#68]
Hi~
This is the code after the predefined is expanded:

struct MODULE_B : ::sc_core::sc_module{
  typedef MODULE_B SC_CURRENT_USER_MODULE; 
  MODULE_B( ::sc_core::sc_module_name ) {
    { ::sc_core::sc_process_handle func_b_handle = sc_core::sc_get_curr_simcontext()->create_method_process( "func_b", false, static_cast<sc_core::SC_ENTRY_FUNC>(&SC_CURRENT_USER_MODULE::func_b), this, 0 ); this->sensitive << func_b_handle; this->sensitive_pos << func_b_handle; this->sensitive_neg << func_b_handle; };
  }
  void func_b();
};

I'm a little curious about the programming syntax of this sentence：“MODULE_B( ::sc_core::sc_module_name ){}".
Why is it possible to use only the name of the class as an argument in the definition of a constructor?
Look forward to your reply, thank you!

**Comment by markfoodyburton** [comment]
I'm not sure I understand your question. Can you show us the SystemC code which isn't working?

**Comment by lmxlovecode** [comment]
Hi~ the code works. But I'm a little confused about the grammar of this sentence：

#define SC_CTOR(user_module_name)                                             \
    typedef user_module_name SC_CURRENT_USER_MODULE;                          \
    user_module_name( ::sc_core::sc_module_name )

The correct syntax for c++ should be: user_module_name( ::sc_core::sc_module_name var)
Why does this place omit a variable name and still work?
Maybe I don't understand c++ well enough, look forward to your reply~

**Comment by markfoodyburton** [comment]
As the manual says, module names are managed by class sc_module_name, not by class sc_module. The sc_module constructor ignores the sc_module_name argument, and so does not name it.

However - the code you are pointing to is old, as far as I can tell. I recommend having a go with the recently released public review of 3.0.0.

**Comment by dcblack** [comment]
It is sneaky if you are interested in the underlying mechanics: The sc_module_name constructor stores a copy of the string in a static member variable. The default constructor for sc_module uses the static member for its construction.

It's really a sad technique designed to reduce the need for non-C++ programmers to understand construction requirements. A feature that allows System"C" to be more "C-like" than "C++-like."

**Comment by lmxlovecode** [comment]
Get~ thanks very much~
