### ISSUE TITLE
no configure file

### ISSUE THREAD

**Issue by edaplayground** [accellera-official/systemc#7]
I'm trying to install 2.3.4 on EDA Playground (in a docker container) and the run is failing because there is no "configure" file. Which, looking at https://github.com/accellera-official/systemc, there isn't. I am following the instructions at https://github.com/accellera-official/systemc/blob/master/INSTALL.md, which is exactly what I did for 2.3.0 to 2.3.3) What am I missing?

Step 13/30 : RUN git clone https://github.com/accellera-official/systemc.git
 ---> Using cache
 ---> dd3c9b94d95d
-- snip --
Step 16/30 : RUN ls -l systemc
 ---> Running in 34525cf7d509
total 196
-rw-r--r-- 1 root root  2195 Jul 30 09:16 AUTHORS.md
-rw-r--r-- 1 root root 38946 Jul 30 09:16 CMakeLists.txt
-rw-r--r-- 1 root root  5640 Jul 30 09:16 CONTRIBUTING.md
-rw-r--r-- 1 root root 30718 Jul 30 09:16 INSTALL.md
-rw-r--r-- 1 root root 11358 Jul 30 09:16 LICENSE
-rw-r--r-- 1 root root  2633 Jul 30 09:16 Makefile.am
-rw-r--r-- 1 root root  3315 Jul 30 09:16 NOTICE
-rw-r--r-- 1 root root  4631 Jul 30 09:16 README.md
-rw-r--r-- 1 root root 34997 Jul 30 09:16 RELEASENOTES
drwxr-xr-x 2 root root  4096 Jul 30 09:16 cmake
drwxr-xr-x 2 root root  4096 Jul 30 09:16 config
-rw-r--r-- 1 root root 22074 Jul 30 09:16 configure.ac
drwxr-xr-x 4 root root  4096 Jul 30 09:16 docs
drwxr-xr-x 6 root root  4096 Jul 30 09:16 examples
drwxr-xr-x 3 root root  4096 Jul 30 09:16 msvc10
drwxr-xr-x 5 root root  4096 Jul 30 09:16 src
Removing intermediate container 34525cf7d509
 ---> c1df43997ad1
Step 17/30 : RUN mkdir -p systemc/objdir
 ---> Running in 81a1c130afd4
Removing intermediate container 81a1c130afd4
 ---> 0215055ffb6d
Step 18/30 : WORKDIR /install_data/systemc/objdir
 ---> Running in 1e838946a3e2
Removing intermediate container 1e838946a3e2
 ---> 0d42f997d8ac
Step 19/30 : RUN mkdir -p /playground_lib/systemc-2.3.4
 ---> Running in 03ac688a2921
Removing intermediate container 03ac688a2921
 ---> e8455ffdb159
-- snip -- 
Step 23/30 : RUN ../configure --prefix=/playground_lib/systemc-2.3.4
 ---> Running in 157f3742ee7a
/bin/sh: 1: ../configure: not found
The command '/bin/sh -c ../configure --prefix=/playground_lib/systemc-2.3.4' returned a non-zero code: 127

**Comment by barnasc** [comment]
SystemC 2.3.4 is not released by Accellera (see https://www.accellera.org/downloads/standards/systemc) so it would be rather confusing for the community to release something under this version number. Actually this repository is based on SystemC 2.3.3 and includes the bug fixes. I suggest we rename the configure script first with the version `2.3.3_fixes` before you publish on EDA playground.
Is there is specific reason why you need this version instead of the latest Accellera stable SystemC 2.3.3 ?

**Comment by edaplayground** [comment]
No. I know very little about SystemC, but had just installed 2.3.3 on EDA Playground and a colleague asked why not 2.3.4. I said, because 2.3.3 was the latest version on the Accelera website and asked where I could find 2.3.4. He pointed me to here. But if it's not officially released then that explains why it's not on the Accelera website and I'll wait until it is released. Thanks for your help.
