### ISSUE TITLE
Rust binding?

### ISSUE THREAD

**Issue by ileixe** [accellera-official/systemc#77]
Hi, we're using systemc a lot and have a large rust codebase. I'd like to ask question about feasibility to make Rust binding for Systemc. Any opinion or prior arts?

**Comment by karthick-gururaj** [comment]
Hi,

I think the Accellera's SystemC forum (https://forums.accellera.org/forum/10-systemc-language/) maybe more appropriate for this. SystemC is C++ - and Rust has bindings to C++ (that you are likely already aware of). But beyond that high level response - a lot will depend on exactly what is modeled (at what level of abstraction) in the rust codebase and how it needs to communicate with the SystemC simulation.

**Comment by lmailletcontoz** [comment]
Rust binding is not part of the IEEE 1666-2023 revision, and is therefore out of scope at the moment. This might be considered for a later revision.
