### ISSUE TITLE
move to cmake, seriously!

### ISSUE THREAD

**Issue by javf88** [accellera-official/systemc#80]
Hi,

This is the second time I worked with a synopsis project. I still dunno why make is enforced when in 2024 we have cmake which is a very powerful generator of makefile.

it is always the synopsis makefile's that consume more and more valuable human power. They are convoluted and not very easy to maintain. Last time, it was a makefile for some neural accelerator and now makefile of systemC.

IMHO, I believe that dropping your makefile approach would be beneficial for your company. I keep having a bad after taste when debugging synopsis's makefiles, and I always say to my managers or purchasing department to avoid synopsis tools due to the unreliability.

I hope the feedback is taken as a constructive criticism.

kind regards,
Jorge Ventura

**Comment by janweinstock** [comment]
Hi Jorge,

have you seen our [CMakeLists.txt](https://github.com/accellera-official/systemc/blob/3.0.0/CMakeLists.txt)?

If you are looking for support regarding Synopsys products, this is not the right place.

Best regards,
Jan
