### ISSUE TITLE
systemc 3.0: Is it Intentional to remove the matched name but remain the removed element by calling sc_object_manager::remove_object?

### ISSUE THREAD

**Issue by zswseu2018** [accellera-official/systemc#90]
E.g. if one sc_object is removed by calling sc_object_manager::remove_object(), then 
-- the corresponding second.m_element_p and second.m_name_origin is reset
-- but the corresponding first's content is kept unchanged, 
-- What's more, the m_instance_table.size is kept unchanged. 

It makes me confused, and I suppose the whole element should be removed from m_instance_table and the table size should be  subtracted by 1. IS my thinking correct?

**Comment by lmailletcontoz** [comment]
It is intentional to keep the names, even if the object is removed. This is not part of the standard, and therefore is implementation-defined.

**Comment by zswseu2018** [comment]
Many thanks for the explanation!
