### ISSUE TITLE
Enhancement: provide mutex etc synchronization facilities in method processes

### ISSUE THREAD

**Issue by 0-issue** [accellera-official/systemc#93]
SystemC seems to have two goals: synthesis-modeling and simulation-modeling.

While discussing differences between method and thread process, a lot of online discussion seems to suggest "method processes are to model combinational logic, and that's why it doesn't support blocking calls like mutex lock". But that is not the full truth even today for method processes from simulation-modeling perspective. Method processes do support "blocking", it's just that the method stack is not maintained. Blocking for something is nothing but waiting for an event, and next_trigger provides exactly that. So there isn't an inherent deficiency with not having a suspended stack, in effect method processes still "block" on next_trigger.

Other old simulation libraries in past have supported synchronization facilities like mutexs, semaphores, fifos with method style processes without any problem. This request is a step towards making method processes usable for real process oriented simulation modeling with resource synchronization. Because without resource synchronization, it's not easy to use it for modeling.

Advantage: For large models, users will be able to significantly lower memory consumption due to lack of a suspended stack per process. This will not only allow simulating larger models, but also speed up simulation.

The listing below shows a possible mutex API to support mutex-synchronization for method processes. ``next_trigger(mutex_obj)`` enqueues the process in the mutex's wait list, and sets next trigger to it's wakeup event. As you can see the method doesn't "block" but still is able to synchronize using a shared mutex. The method case labels represent phases a process is in. Let's assume we are in a single threaded mode. There are other ways this API can be designed without requiring a suspended stack.

Once there is an agreement that we want to pursue this, the API for all of mutex, semaphore and fifo can be discussed. Thanks!

```cpp
void method_proc() {
    switch (phase) {
        ...
        case pre_mutex:
            do_pre_mutex();
            phase = critical_section;
            next_trigger(mutex_obj);
            break;
        case critical_section:
            do_critical();
            phase = post_mutex;
            mutex_obj.release();
            next_trigger(0, SC_SEC);
            break;
        case post_mutex:
            do_post_mutex();
            phase = whatever;
            next_trigger(whatever_trigger);
            break;
        ...
    };
};
```

**Comment by lmailletcontoz** [comment]
Thanks for the inputs. This topic is considered as low priority by the working group.
