### ISSUE TITLE
sc_bigint::xor_reduce incorrect result

### ISSUE THREAD

**Issue by mpardalos** [accellera-official/systemc#95]
The following two functions produce different results under systemc 3.0.0:

```c++
bool f1() {
    sc_dt::sc_uint<3> x0;
    x0 = sc_dt::sc_bigint<3>(-1);
    return x0.xor_reduce(); // returns 0
}

bool f2() {
    sc_dt::sc_uint<3> x0 = sc_dt::sc_bigint<3>(-1);
    return x0.xor_reduce(); // returns 1
}
```

I assume that x0 would contain the value `3'b111` so the xor_reduce should produce `1'b1` in both cases.

Running this under SystemC 2.3.4 agrees with this interpretation, with both functions returning `1'b1`

Looks to me like there is some issue with `sc_bigint::operator=`.

**Comment by AndrewGoodrich** [comment]
This is definitely a bug, there is a missing call to extend_sign() to trim the value being assigned. It will be fixed in 3.01
